<?php

/**
 * @file
 * Change the Bootstrap CDN theme according to light or dark mode.
 */

use Drupal\bootstrap\Bootstrap;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function d8_night_block_view_dark_mode_switch_block_alter(
  array &$build,
  BlockPluginInterface $block
) {
  $build['#attached']['library'][] = 'd8_night/base';

  $theme = Bootstrap::getTheme('d8_theme')->getSetting('cdn_theme');
  $build['#attached']['drupalSettings']['d8_night'] = $theme === 'slate';
}
