<?php

/**
 * @file
 * Provides a wrapper for the StandWithUkraine module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function d8_standwithukraine_page_attachments_alter(array &$attachments) {
  if (
    !empty($theme = \Drupal::config('system.theme')->get('admin')) &&
    \Drupal::theme()->getActiveTheme()->getName() === $theme &&
    \Drupal::config('standwithukraine.settings')->get('single')
  ) {
    foreach ($attachments['#attached']['html_head'] as &$element) {
      if ($element[1] === 'standwithukraine') {
        $element[0]['#value'] = str_replace(2.5, 4, $element[0]['#value']);
      }
    }
  }
}

/**
 * Implements hook_page_top().
 */
function d8_standwithukraine_page_top(array &$page_top) {
  if (
    !empty($theme = \Drupal::config('system.theme')->get('admin')) &&
    \Drupal::theme()->getActiveTheme()->getName() === $theme
  ) {
    $page_top['standwithukraine']['#single'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d8_standwithukraine_preprocess_standwithukraine(&$variables) {
  if (
    empty($theme = \Drupal::config('system.theme')->get('admin')) ||
    \Drupal::theme()->getActiveTheme()->getName() !== $theme
  ) {
    return;
  }

  /** @var \Drupal\Core\Menu\LocalTaskManagerInterface $service */
  $service = \Drupal::service('plugin.manager.menu.local_task');

  $route_name = \Drupal::routeMatch()->getRouteName();
  $offset = 85;

  if ($route_name !== 'system.batch_page.html') {
    $offset += 32;
    $items = $service->getLocalTasksForRoute($route_name);

    foreach ($items as $group_delta => &$group) {
      /** @var \Drupal\Core\Menu\LocalTaskInterface $item */
      foreach ($group as $item_delta => $item) {
        if ($item->getRouteName() === $route_name) {
          unset($group[$item_delta]);
        }
      }

      if (empty($group)) {
        unset($items[$group_delta]);
      }
    }

    if (!empty($items)) {
      $offset += 51;
    }
  }

  /** @var \Drupal\Core\Template\Attribute $attributes */
  $attributes = $variables['attributes'];

  $attributes
    ->addClass('right')
    ->setAttribute('style', 'top: ' . $offset . 'px');
}
