<?php

/**
 * @file
 * Install, update and uninstall functions for the d8_captcha module.
 */

/**
 * Uninstall the "reCAPTCHA Preloader" module.
 */
function d8_captcha_update_8001() {
  \Drupal::moduleHandler()->loadInclude('install', 'd8');
  _d8_module('recaptcha_preloader', NULL, TRUE);
}

/**
 * Install the "reCAPTCHA Preloader" module.
 */
function d8_captcha_update_9501() {
  \Drupal::moduleHandler()->loadInclude('install', 'd8');
  _d8_module('recaptcha_preloader');
}
