<?php

/**
 * @file
 * Provides a wrapper for the reCAPTCHA module.
 */

/**
 * Implements hook_captcha_alter().
 */
function d8_captcha_captcha_alter(array &$captcha, array $info): void {
  if ($info['captcha_type'] === 'reCAPTCHA') {
    if ($info['module'] === 'recaptcha') {
      $captcha['form']['recaptcha_widget']['#suffix'] = '';
    }
    elseif (
      $info['module'] === 'recaptcha_preloader' &&
      isset($captcha['form']['#attached']['library'])
    ) {
      unset($captcha['form']['#attached']['library']);
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function d8_captcha_library_info_alter(array &$libraries, string $extension): void {
  if (
    $extension === 'recaptcha' &&
    isset($libraries[$name = $extension . '.invisible'])
  ) {
    /** @var \Drupal\Core\Extension\ExtensionPathResolver $resolver */
    $resolver = \Drupal::service('extension.path.resolver');

    $path = $resolver->getPath('module', 'd8_captcha');

    $libraries[$name]['js'] = ['/' . $path . '/js/' . $name . '.js' => []];
  }
}
