name: D8+ Config Export to PHP array
description: Provides a wrapper for the Config Export to PHP array module.
package: D8+

type: module
core_version_requirement: '>=11'

dependencies:
  - d8:d8 (>=0.23.0.202)
  - config2php:config2php

hidden: true

lifecycle: deprecated
lifecycle_link: https://github.com/ohorbatiuk/d8/issues/377
