<?php

/**
 * @file
 * Provides a wrapper for the "Config Export to PHP array" module.
 */

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function d8_config2php_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  if ($route_name === 'help.page.d8_config2php') {
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provides a wrapper for the "Config Export to PHP array" module.') . '</p>';
  }

  return $output;
}
