name: D8+ Config Export to PHP array
description: Provides a wrapper for the Config Export to PHP array module.
package: D8+

type: module
core_version_requirement: '>=11'

dependencies:
  - and:and (>=0.23.0.202)
  - config2php:config2php
