<?php

/**
 * @file
 * Provides a wrapper for the Drupal Symfony Mailer module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\d8_mail\Entity\MailerTransport;

/**
 * Implements hook_entity_type_alter().
 */
function d8_mail_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $entity_types['mailer_transport']->setClass(MailerTransport::class);
}

/**
 * Implements hook_help().
 */
function d8_mail_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  if ($route_name === 'help.page.d8_mail') {
    $output .= '<h3>' . t('About') . '</h3>';

    $output .= '<p>';

    $url = Url::fromRoute('help.page', ['name' => 'symfony_mailer']);

    $output .= t(
      'Provides a wrapper for the <a href=":url">:name</a> module.',
      [
        ':url' => $url->toString(),
        ':name' => 'Drupal Symfony Mailer'
      ]
    );

    $output .= '</p>';
  }

  return $output;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d8_mail_preprocess_email_wrap__d8(&$variables) {
  $variables['logo'] = sprintf(
    str_repeat('%s', 2),
    \Drupal::request()->getSchemeAndHttpHost(),
    theme_get_setting('logo')['url']
  );

  /** @var \Drupal\symfony_mailer\InternalEmailInterface $email */
  $email = $variables['email'];

  if (
    is_array($parameter = $email->getParam('legacy_message')) &&
    isset($parameter['params']['account'])
  ) {
    $account = $parameter['params']['account'];
  }
  else {
    $account = $email->getAccount();
  }

  $variables['welcome'] = t(
    'Hello @recipient-name,',
    ['@recipient-name' => $account->getDisplayName()]
  );

  /** @var \Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
  $date_formatter = \Drupal::service('date.formatter');

  $variables['year'] = $date_formatter->format(
    \Drupal::time()->getRequestTime(),
    'html_year'
  );

  $variables['site_name'] = \Drupal::config('system.site')->get('name');
}

/**
 * Implements hook_theme().
 */
function d8_mail_theme($existing, $type, $theme, $path) {
  $name = 'email_wrap';
  return [$name . '__d8' => ['base hook' => $name]];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function d8_mail_theme_suggestions_email_wrap_alter(
  array &$suggestions,
  array $variables
) {
  if ($variables['is_html']) {
    $suggestions[] = $variables['theme_hook_original'] . '__d8';
  }
}
