<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function d8_mail_preprocess_email_wrap__d8(&$variables) {
  $variables['logo'] = \Drupal::request()->getSchemeAndHttpHost();
  $variables['logo'] .= theme_get_setting('logo')['url'];

  /** @var \Drupal\symfony_mailer\InternalEmailInterface $email */
  $email = $variables['email'];

  if (
    is_array($parameter = $email->getParam('legacy_message')) &&
    isset($parameter['params']['account'])
  ) {
    $account = $parameter['params']['account'];
  }
  else {
    $account = $email->getAccount();
  }

  $variables['welcome'] = t(
    'Hello @recipient-name,',
    ['@recipient-name' => $account->getDisplayName()]
  );

  /** @var \Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
  $date_formatter = \Drupal::service('date.formatter');

  $variables['year'] = $date_formatter->format(
    \Drupal::time()->getRequestTime(),
    'html_year'
  );

  $variables['site_name'] = \Drupal::config('system.site')->get('name');
}

/**
 * Implements hook_theme().
 */
function d8_mail_theme($existing, $type, $theme, $path) {
  $name = 'email_wrap';
  return [$name . '__d8' => ['base hook' => $name]];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function d8_mail_theme_suggestions_email_wrap_alter(array &$suggestions, array $variables) {
  if ($variables['is_html']) {
    $suggestions[] = $variables['theme_hook_original'] . '__d8';
  }
}
