<?php

/**
 * @file
 * Provides a wrapper for the Drupal Symfony Mailer module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function d8_mail_help(
  string $route_name,
  RouteMatchInterface $route_match
): string {
  $output = '';

  if ($route_name === 'help.page.d8_mail') {
    $output .= '<h3>' . t('About') . '</h3>';

    $output .= '<p>';

    $url = Url::fromRoute('help.page', ['name' => 'symfony_mailer']);

    $output .= t(
      'Provides a wrapper for the <a href=":url">:name</a> module.',
      [
        ':url' => $url->toString(),
        ':name' => 'Drupal Symfony Mailer',
      ],
    );

    $output .= '</p>';
  }

  return $output;
}

/**
 * Implements hook_library_info_alter().
 */
function d8_mail_library_info_alter(array &$libraries, string $extension): void {
  if ($extension === 'symfony_mailer') {
    unset($libraries['test']['css']['theme']['css/test.email.css']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d8_mail_preprocess_email_wrap__html(array &$variables): void {
  $variables['logo'] = sprintf(
    str_repeat('%s', 2),
    \Drupal::request()->getSchemeAndHttpHost(),
    theme_get_setting('logo')['url'],
  );

  /** @var \Drupal\symfony_mailer\InternalEmailInterface $email */
  $email = $variables['email'];

  if (
    is_array($parameter = $email->getParam('legacy_message')) &&
    isset($parameter['params']['account'])
  ) {
    $account = $parameter['params']['account'];
  }
  else {
    $account = $email->getAccount();
  }

  $variables['welcome'] = t(
    'Hello @recipient-name,',
    ['@recipient-name' => $account->getDisplayName()],
  );

  /** @var \Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
  $date_formatter = \Drupal::service('date.formatter');

  $variables['year'] = $date_formatter->format(
    \Drupal::time()->getRequestTime(),
    'html_year',
  );

  $variables['site_name'] = \Drupal::config('system.site')->get('name');
}

/**
 * Implements hook_theme().
 */
function d8_mail_theme(
  array $existing,
  string $type,
  string $theme,
  string $path
): array {
  $name = 'email_wrap';
  return [$name . '__html' => ['base hook' => $name]];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function d8_mail_theme_suggestions_email_wrap_alter(
  array &$suggestions,
  array $variables
): void {
  if ($variables['is_html']) {
    $suggestions[] = $variables['theme_hook_original'] . '__html';
  }
}
